version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    #volumes:
      #- ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=next
      - MYSQL_DATABASE=next
      - MYSQL_USER=next

  redis:
    image: redis:4.0-alpine
    environment:
      - "TZ=Europe/Paris"
    restart: always
  
  nextcloud:
    build: fpm-alpine
    ports:
      - 80:80
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - MYSQL_HOST=db
      - MYSQL_DATABASE=next
      - MYSQL_USER=next
      - MYSQL_PASSWORD=next
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
      
